### ISSUE TITLE
帮忙看下这个错误的原因吧

### ISSUE THREAD

**Issue by lilihua** [weiboad/kafka-php#102]
PHP Notice:  Undefined variable: memberId in /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php on line 357
PHP Notice:  Undefined offset: 1 in /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Consumer/Assignment.php on line 130
PHP Fatal error:  Uncaught exception 'Kafka\Exception\Protocol' with message 'given data invalid. `assignments` is undefined.' in /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php:128
Stack trace:
#0 [internal function]: Kafka\Protocol\SyncGroup->encodeGroupAssignment(Array)
#1 /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php(538): call_user_func(Array, Array)
#2 /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php(60): Kafka\Protocol\Protocol::encodeArray(Array, Array)
#3 /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Protocol.php(139): Kafka\Protocol\SyncGroup->encode(Array)
#4 /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(347): Kafka\Protocol::encode(14, Array)
#5 /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(88): Kafka\Consumer\Process->syncGroup()
#6 [internal function]: Kafka\Consumer\Process->Kafka\Consumer\{closure}()
# in /var/www/html/dl-test.kmapp.cn/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php on line 128

**Comment by nmred** [comment]
@lilihua you can use newr version, this issue has fixed

**Comment by zplzpl** [comment]
Undefined variable: memberId
"nmred/kafka-php": "0.2.*"

**Comment by zplzpl** [comment]
#0 /vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(357): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/data/www/...', 357, Array)
#1 /vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(185): Kafka\Consumer\Process->failSyncGroup(27)

**Comment by zplzpl** [comment]
public function failSyncGroup($errorCode)
    {
        $error = sprintf('Sync group fail, need rejoin, errorCode %d, memberId: %s', $errorCode, $memberId);
        $this->error($error);
        $this->stateConvert($errorCode);
    }

**Comment by nmred** [comment]
@zplzpl  提供一下kafka server 版本信息

**Comment by zplzpl** [comment]
我觉得跟KAFKA版本没有关系，

public function failSyncGroup($errorCode)
{
    $error = sprintf('Sync group fail, need rejoin, errorCode %d, memberId: %s', $errorCode, $memberId);
    $this->error($error);
    $this->stateConvert($errorCode);
}

这个方法中的memberId 没有定义就调用了。应该改成如下就可以了吧：

    public function failSyncGroup($errorCode)
    {
        $assign = \Kafka\Consumer\Assignment::getInstance();
        $memberId = $assign->getMemberId();
        $error = sprintf('Sync group fail, need rejoin, errorCode %d, memberId: %s', $errorCode, $memberId);
        $this->error($error);
        $this->stateConvert($errorCode);
    }

**Comment by nmred** [comment]
@zplzpl 这块确实存在调用未定义变量的问题，但是不是的这个问题的根本原因，你详细提供一下你的kafkabroker 版本和你代码中 setBrokerVersion 版本，我才好定位问题。。。。。

**Comment by zplzpl** [comment]
"0.10.2.0"

感谢你的认真啊

**Comment by nmred** [comment]
报的 error Code 是 27 ，代表正在 rebalance , 应该是吧这个notice错误修复了就可以消费成功，我修复一下这个notice, 感谢

**Comment by niedachui1** [comment]
nmred / kafka-php 中密码认证有吗？
