### ISSUE TITLE
直接执行consumer.php的代码报错

### ISSUE THREAD

**Issue by zhongjq** [weiboad/kafka-php#105]
PHP Fatal error:  Uncaught Kafka\Exception\Protocol: given data invalid. `assignments` is undefined. in /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php:                                                         128
Stack trace:
#0 [internal function]: Kafka\Protocol\SyncGroup->encodeGroupAssignment(Array)
#1 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php(538): call_user_func(Array, Array)
#2 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php(60): Kafka\Protocol\Protocol::encodeArray(Array, Array)
#3 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol.php(139): Kafka\Protocol\SyncGroup->encode(Array)
#4 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(347): Kafka\Protocol::encode(14, Array)
#5 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(88): Kafka\Consumer\Process->syncGroup()
#6 [internal function]: Kafka\Consumer\Process->Kafka\Consumer\{closure}()
#7 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Consumer/State.php(136): call_user_fu in /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php on line

**Comment by zhongjq** [comment]
topic 要是存在的

**Comment by a5420bc** [comment]
当一个topic只有一个分区时,使用system函数同时开启php进程消费该topic,出现以上日志报错。当有时间间隔开启时,两个进程消费的数据相同。
