### ISSUE TITLE
使用多进程消费同一个topic报错

### ISSUE THREAD

**Issue by a5420bc** [weiboad/kafka-php#110]
PHP Fatal error: Uncaught Kafka\Exception\Protocol: given data invalid. assignments is undefined. in /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php: 128
Stack trace:
#0 [internal function]: Kafka\Protocol\SyncGroup->encodeGroupAssignment(Array)
#1 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php(538): call_user_func(Array, Array)
#2 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php(60): Kafka\Protocol\Protocol::encodeArray(Array, Array)
#3 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol.php(139): Kafka\Protocol\SyncGroup->encode(Array)
#4 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(347): Kafka\Protocol::encode(14, Array)
#5 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php(88): Kafka\Consumer\Process->syncGroup()
#6 [internal function]: Kafka\Consumer\Process->Kafka\Consumer{closure}()
#7 /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Consumer/State.php(136): call_user_fu in /vagrant/settlement/vendor/nmred/kafka-php/src/Kafka/Protocol/SyncGroup.php on line

brokerVersion:0.9.0.1
当一个topic只有一个分区时,使用system函数同时开启php进程消费该topic,出现以上日志报错。当有时间间隔开启时,两个进程消费的数据相同。

**Comment by nmred** [comment]
v0.2.0.5 已修复
