### ISSUE TITLE
积压消息过多，内存超出大小程序退出无法启动

### ISSUE THREAD

**Issue by liufang** [weiboad/kafka-php#111]
当kafka积压了大量消息的时候，客户端消费获取消息过多， 导致内存超出限制程序退出， 并且无法启动正常工作。

**Comment by nmred** [comment]
是 example的consumer可以复现吗？

**Comment by nmred** [comment]
试着更新到 0.2.0.5 

增加 maxBytes 参数的控制：

```
$config->setMaxBytes(64* 1024);
```

把这个参数设置小点试试
