### ISSUE TITLE
启动consumer脚本，开启第二个时候，报大量的错

### ISSUE THREAD

**Issue by jefflili** [weiboad/kafka-php#112]
6-20 13:59:16"PHP Notice:  Undefined index: context in /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/State.php on line 182
PHP Stack trace:
PHP   1. {main}() /root/Jeff/kafka/consumer.php:0
PHP   2. Kafka\Consumer->start() /root/Jeff/kafka/consumer.php:69
PHP   3. Amp\run() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer.php:77
PHP   4. Amp\NativeReactor->run() /root/Jeff/kafka/vendor/amphp/amp/lib/functions.php:46
PHP   5. Amp\NativeReactor->doTick() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:71
PHP   6. Amp\NativeReactor->selectActionableStreams() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:214
PHP   7. Amp\NativeReactor->doIoCallback() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:249
PHP   8. call_user_func:{/root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265}() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265
PHP   9. Kafka\Socket->Kafka\{closure}() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265
PHP  10. Kafka\Socket->read() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:252
PHP  11. call_user_func:{/root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372}() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372
PHP  12. Kafka\Consumer\Process->Kafka\Consumer\{closure}() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372
PHP  13. Kafka\Consumer\Process->processRequest() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:69
PHP  14. Kafka\Consumer\Process->succFetch() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:206
PHP  15. Kafka\Consumer\State->succRun() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:640
PHP Notice:  Undefined index: context in /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/State.php on line 182
PHP Stack trace:
PHP   1. {main}() /root/Jeff/kafka/consumer.php:0
PHP   2. Kafka\Consumer->start() /root/Jeff/kafka/consumer.php:69
PHP   3. Amp\run() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer.php:77
PHP   4. Amp\NativeReactor->run() /root/Jeff/kafka/vendor/amphp/amp/lib/functions.php:46
PHP   5. Amp\NativeReactor->doTick() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:71
PHP   6. Amp\NativeReactor->selectActionableStreams() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:214
PHP   7. Amp\NativeReactor->doIoCallback() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:249
PHP   8. call_user_func:{/root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265}() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265
PHP   9. Kafka\Socket->Kafka\{closure}() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265
PHP  10. Kafka\Socket->read() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:252
PHP  11. call_user_func:{/root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372}() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372
PHP  12. Kafka\Consumer\Process->Kafka\Consumer\{closure}() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372
PHP  13. Kafka\Consumer\Process->processRequest() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:69
PHP  14. Kafka\Consumer\Process->succFetch() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:206
PHP  15. Kafka\Consumer\State->succRun() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:640
PHP Notice:  Undefined index: context in /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/State.php on line 182
PHP Stack trace:
PHP   1. {main}() /root/Jeff/kafka/consumer.php:0
PHP   2. Kafka\Consumer->start() /root/Jeff/kafka/consumer.php:69
PHP   3. Amp\run() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer.php:77
PHP   4. Amp\NativeReactor->run() /root/Jeff/kafka/vendor/amphp/amp/lib/functions.php:46
PHP   5. Amp\NativeReactor->doTick() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:71
PHP   6. Amp\NativeReactor->selectActionableStreams() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:214
PHP   7. Amp\NativeReactor->doIoCallback() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:249
PHP   8. call_user_func:{/root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265}() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265
PHP   9. Kafka\Socket->Kafka\{closure}() /root/Jeff/kafka/vendor/amphp/amp/lib/NativeReactor.php:265
PHP  10. Kafka\Socket->read() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:252
PHP  11. call_user_func:{/root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372}() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372
PHP  12. Kafka\Consumer\Process->Kafka\Consumer\{closure}() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Socket.php:372
PHP  13. Kafka\Consumer\Process->processRequest() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:69
PHP  14. Kafka\Consumer\Process->succFetch() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:206
PHP  15. Kafka\Consumer\State->succRun() /root/Jeff/kafka/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:640

**Comment by jefflili** [comment]
我这边的配置是13个分区，版本号：0.10.1.1

**Comment by nmred** [comment]
#104  You can try new version client
