### ISSUE TITLE
Kafka\Exception no data 

### ISSUE THREAD

**Issue by gongdianpeng** [weiboad/kafka-php#156]
[Kafka\Exception]
  Unexpected EOF while reading 4 bytes from stream (no data)

这个改如何解决

SocketSync 310行

**Comment by lcobucci** [comment]
@gongdianpeng can you please add more information about what you're doing (in English, please)? A stack trace would also be very helpful (and the version you're using).

**Comment by gongdianpeng** [comment]
@lcobucci  have been resolved. thanks 

Producer brokerList  I made mistake in writing~
