### ISSUE TITLE
vendor/autoload.php missing in examples

### ISSUE THREAD

**Issue by aurovrata** [weiboad/kafka-php#166]
The examples are including 
`require '../vendor/autoload.php';`
which is not available as part of the repo.  I am assuming it is a std autoload.

**Comment by lcobucci** [comment]
@aurovrata before of executing the provided examples you must install the project dependencies via composer, which is done by simply running `composer install` on the root folder for the library.

**Comment by lcobucci** [comment]
(and also a running Kafka server, sure)

**Comment by aurovrata** [comment]
thanks, got it to work just fine.
