### ISSUE TITLE
broker.php中没有error方法，有异常会报错

### ISSUE THREAD

**Issue by fendouxiong** [weiboad/kafka-php#171]
[error] 538#0: *455777 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Kafka\Broker::error() in /WWW/RRKDInterface/vendor/rrkd/php-kafka/src/Broker.php on line 196" while reading response header from upstream

**Comment by lcobucci** [comment]
@fendouxiong are you using this lib? I mean, it looks like you're using a fork - based on the path which composer installed it (`vendor/rrkd/php-kafka`).

Can you please check which version you're using in your `composer.json`?

**Comment by fendouxiong** [comment]
@lcobucci I download this package (weiboad/kafka-php) to my private store，then  use it with php 5.4 ，not change anything 。

composer.json
`{
  "name": "rrkd/php-kafka",
  "description": "kafka",
  "keywords": [
    "kafka"
  ],
  "require": {
    "php": ">=5.4"
  },
  "autoload": {
    "psr-4": {
      "Kafka\\": "src/"
    }
  }
}`

maybe about php version, but  i use it with php 7.2 ,there also no this function (Broker::error())

**Comment by lcobucci** [comment]
@fendouxiong we have a trait which provides that method, maybe `Broker` was relying on it and got changed. Can you pinpoint the exact commit id which you're using? It's possible that you're using a very very very old version which is possibly not maintained anymore...

I'm using the latest commit of `master` in production and it's being quite stable, maybe you can fork from that...

**Comment by fendouxiong** [comment]
Broker.php  not have parent class   and  "__call" function . “this->error()” Where does it come from？

**Comment by lcobucci** [comment]
@fendouxiong if could you tell us which commit you're using we can help you to understand what's going on there, but without that we can't do much. We had issues in the past which were already fixed...

**Comment by fendouxiong** [comment]
@lcobucci  i m sorry,   i delete "use \Kafka\LoggerTrait;" in SingletonTrait , so not fund error function , now i fix it.   thanks for your help.

**Comment by lcobucci** [comment]
@fendouxiong alright... closing as `invalid` then
