### ISSUE TITLE
Missing parentheses in function checkRun at Comsumer/State.php#322, v0.2.0.8

### ISSUE THREAD

**Issue by chongchaoyu** [weiboad/kafka-php#172]
Is it missing parentheses in function checkRun at Comsumer/State.php#322? Because "&" has a lower precedence than "==". I found it has been fixed at master branch.
///------
case self::REQUEST_METADATA:
                if (**$status & self::STATUS_PROCESS** == self::STATUS_PROCESS) {
                    return false;
                }
                if (($status & self::STATUS_LOOP) == self::STATUS_LOOP) {
                    return true;
                }
                return false;
///------

**Comment by chongchaoyu** [comment]
Is it not an issue? why no response for it?

**Comment by lcobucci** [comment]
@chongchaoyu sorry, I just didn't get to reply to you... this is indeed an issue, can you please send a PR to fix it?

**Comment by chongchaoyu** [comment]
@lcobucci I have created 2 PRs, one is for 0.2.0-dev, and the other is for 0.3.0-dev,  please review them.

**Comment by lcobucci** [comment]
Handled in #182
