### ISSUE TITLE
Shouldn't there be a warning when producing to non existing topic?

### ISSUE THREAD

**Issue by simPod** [weiboad/kafka-php#176]
I'm new to kafka but when I'm trying to send message to topic that doesn't exist, shouldn't I get warning? Just checking `SyncProces->convertMessage()` where topics list is fetched and it simply returns empty array when topic does not exist

**Comment by lcobucci** [comment]
@simPod AFAIK the Java CLI consumer/producer creates the topic automatically when it doesn't exist, we don't do anything regarding this yet.

I agree that the lib should emit an error or create the topic (with only 1 partition and 1 as replication factor) based on a given configuration

**Comment by lcobucci** [comment]
This relates to #122 (in a way)

**Comment by lcobucci** [comment]
Handled in #181
