### ISSUE TITLE
Consumer Groups

### ISSUE THREAD

**Issue by trickleup** [weiboad/kafka-php#18]
Hi,

I'm trying to use this library to access the high level consumer api. I'm doing something like: 

```
$consumer->setGroup('group1');
$consumer->setTopic('topic1');
$iterator = $consumer->fetch();
```

Then I create a topic with 5 partitions (1 replica), run two processes of the consumer, and then start producing some random messages to different partitions. All messages end up in both consumers. Since they use the same consumer group, I was expecting the messages (via their partitions) to be distributed to the two processes. Is this not the case? Are there additional steps I have to take to make this work?

Producer code looks like:

```
$producer->setRequireAck(-1);
$producer->setMessages($topic, $partition, $messages);
$producer->send();
```

Sorry for any misunderstandings on my behalf of the kafka protocol, or this library - but any help would be greatly appreciated!

**Comment by Timandes** [comment]
I think you should give partition number even when consuming.

> Kafka is able to provide both ordering guarantees and load balancing over a pool of consumer processes. This is achieved by assigning the partitions in the topic to the consumers in the consumer group so that each partition is consumed by exactly one consumer in the group. By doing this we ensure that the consumer is the only reader of that partition and consumes the data in order. Since there are many partitions this still balances the load over many consumer instances. Note however that there cannot be more consumer instances than partitions.

![A two server Kafka cluster hosting four partitions (P0-P3) with two consumer groups. Consumer group A has two consumer instances and group B has four.](http://kafka.apache.org/images/consumer-groups.png)

[Apache Kafka Documentation](http://kafka.apache.org/documentation.html)

**Comment by git-hulk** [comment]
hi @Timandes, why have to assign partition when consuming, while i saw registerConsumer function in  `ZooKeeper.php`.

**Comment by lnparker** [comment]
hi @Timandes , i agree with @git-hulk, there is no need to specify the partition num when consuming. The consuming progress should be able to consumue from multiple partitions. Please check.

**Comment by appasahebs** [comment]
But its not working in my case as well, same messages are on both consumers with that respect to the group. Did it worked for you? @git-hulk and @lnparker

**Comment by nmred** [comment]
Hi, @trickleup 

You can try using the new version， v0.2.0 has support auto consumer group rebalance
