### ISSUE TITLE
Batch consume

### ISSUE THREAD

**Issue by simPod** [weiboad/kafka-php#180]
If I want to consume in batches, how would you approach this?

I found that it's possilbe to set `auto.commit.enable = false` to consumer and commit manually so theoretically, I could be consuming eg 10K messages into a buffer and after processing them do the commit.

Is there a way to set this option to consumer? Or different approach? 

Thanks!

**Comment by simPod** [comment]
So in there `groupId` mentioned https://github.com/weiboad/kafka-php/blob/master/docs/Configure.md. In official documentation https://kafka.apache.org/documentation.html#consumerconfigs, its name is `group.id`

I suppose we don't have `enable.auto.commit`. I tried to figure how, how these work but honestly was not able to find a way to add it here...

**Comment by simPod** [comment]
I worked on something that might make it possilbe in a proper "kafka-way"

**Comment by parveenbadoni** [comment]
> I worked on something that might make it possilbe in a proper "kafka-way"

What change did you make? I also want to change enable.auto.commit to false.

**Comment by simPod** [comment]
Sorry, don't remember, not using this lib anymore.
