### ISSUE TITLE
Publishing and consuming does not work with Kafka 1.0.0

### ISSUE THREAD

**Issue by smarijic** [weiboad/kafka-php#190]
Running Kafka 1.0.0 with Zookeeper on Docker. I am using basic example
````
$config = ProducerConfig::getInstance();
$config->setMetadataBrokerList('172.18.0.2:9092'); //Kafka broker IP
$config->setBrokerVersion('1.0.0');

$producer =  new Producer();
$producer->setLogger($logger);
````

No connection exception is thrown but syncMeta() call returns empty brokers and topics.

When I run this I get following in the log:
`
[2018-02-09 10:42:14] app.DEBUG: Start sync metadata request [] []
[2018-02-09 10:42:14] app.DEBUG: Start sync metadata request params:["esd"] [] []
[2018-02-09 10:42:14] app.DEBUG: Start Request ClientId: kafka-php ApiKey: MetadataRequest  ApiVersion: 0 [] []
`

**Comment by lcobucci** [comment]
@smarijic I'm using `master` in production with Kafka 1.0 and I don't have any issue to produce/consume messages... You can also see our functional tests working on kafka 0.9 and higher (using a simple docker setup as well).

**Comment by lcobucci** [comment]
@smarijic is this solved?

**Comment by smarijic** [comment]
@lcobucci Yes, it turns out there was something wrong with network configuration in docker.
