### ISSUE TITLE
The group is rebalancing, so a rejoin is needed

### ISSUE THREAD

**Issue by simPod** [weiboad/kafka-php#191]
These errors started to pop in my log few hours ago. I wonder whether it even means something is wrong and what can I do about it? Have you ever encountered such thing?

Probably it is related or means the same as Heartbeat error, errorCode:27 that started popping too.

**Comment by lcobucci** [comment]
@simPod I did see this happening on previous versions, but not on `dev-master` (which is what I'm using in prod - shaaaame 😂 )

**Comment by simPod** [comment]
Using dev-master in prod too 😂 But it's happening there. Trying to find the cause...

**Comment by lcobucci** [comment]
Huumm weird... it might be related to having multiple connections to different brokers and some stuff having in one broker and other stuff in another?

**Comment by simPod** [comment]
Have only one broker for now 🤔 I was thinking I'm somehow overloading it so that there might be need for another broker. This is not getting better :D
