### ISSUE TITLE
The code is not complete！！！

### ISSUE THREAD

**Issue by zwxhenu** [weiboad/kafka-php#199]
I want to find Amp\Loop and Psr\Log\LoggerAwareTrait; But I can not find it in the code~~

**Comment by lcobucci** [comment]
@zwxhenu did you use `composer` to install the library? It will download every package that this library depends upon automatically. More info: [getcomposer.org](https://getcomposer.org)

**Comment by zwxhenu** [comment]
@lcobucci oh oh~ ok thanks .

**Comment by lcobucci** [comment]
@zwxhenu I'll be closing this issue as `invalid` since it's not related to the library but rather how it has to be installed. I'll open an issue to improve wording in docs and make things clearer.
