### ISSUE TITLE
Producer的负载均衡怎么做?

### ISSUE THREAD

**Issue by Jiacheng-z** [weiboad/kafka-php#204]
现在消息只会落到一个 consumer 上. 有办法在不知道 consumer数量的情况下自动的随机到不同的 partitions上么?
好像在消息结构中可以通过 `partId` 可以指定需要使用的 partitions , 但是不知道从哪里获取 topic中现有的 consumer 数量.

**Comment by jinguoxing** [comment]
你设置了几个分区，然后可以开几个消费进程，每个消费进程的的组名设置成一样

 $config->setGroupId('test');

可以自动均衡的。
