### ISSUE TITLE
function call, to send messages

### ISSUE THREAD

**Issue by matesio** [weiboad/kafka-php#209]
Hi i am trying to make a function working with kafka stream, but unable to figure out how to do this.
The main goal is to send data continuously through kafka stream , but i can only find single message sample. Can you please share some sample in which you have continuos messages like this,

```php
$producer = new \Kafka\Producer(
    function() {
        return [
            [
                'topic' => 'test',
                'value' => function($arg1,$arg2,arg3,arg4)
                'key' => 'Message key',
            ],
        ];
    }
);
```

it  is sending null messages to broker, rather than calling and send that message,
Thanks

**Comment by matesio** [comment]
ah, i am so stupid, my function was returning nothing, and all the time i was thinking, i am writing kafka-php wrong way.

**Comment by lcobucci** [comment]
@matesio hey don't be so harsh on you, our lib is a bit complicated to use and it's quite error-prone. On top of that we're all humans and we make mistakes 👍 

Let us know if there's anything we can do to help you!
