### ISSUE TITLE
Key is not used for partitionning

### ISSUE THREAD

**Issue by mantzas** [weiboad/kafka-php#228]
I have added the 'key' to the payload, which is the ID of one of my entities, so that i get the same entity in the same partition. Our topic has 4 partitions. Unfortunately it does not seem to work.
We expect that with the above the message will always go in one of the 4 partitions, but we have seen that the message will be send to all partitions.
Do you have any idea with this is the case?

**Comment by mantzas** [comment]
@lcobucci why do we do this client side? does kafka do this already?

**Comment by lcobucci** [comment]
@mantzas nope, that's why I'm asking you to check that particular branch. I'll be reviewing it further this week to integrate, but will be only available in v3.x

**Comment by mantzas** [comment]
@lcobucci yes, this is what's needed from our side. We integrated the current code in our codebase to make this work now. We will wait until v3 to get the library then. Thanks man

**Comment by mantzas** [comment]
@demyanovs done this already based on #218. it's running in production already. thanks.
