### ISSUE TITLE
timestamp is "-1"

### ISSUE THREAD

**Issue by icepigss** [weiboad/kafka-php#230]
`$config = \Kafka\ProducerConfig::getInstance();`
`$config->setMetadataRefreshIntervalMs(10000);`
`$config->setMetadataBrokerList($hostsList);`
`$config->setBrokerVersion('1.0.0');`
`$config->setRequiredAck(1);`
`$config->setClientId($clientId ?: 'kafka-php');`
`$config->setProduceInterval(500);`
`$this->_producer = new \Kafka\Producer();`

 `$ret = $this->_producer->send([ [ 'topic' => 'hello,  'value' => $data, 'key' => ''] ]);`

I don't know where something went wrong.
I got my message but it's field "timestamp" is "-1".

**Comment by pravinkucha** [comment]
explicitly pass message timestamp
