### ISSUE TITLE
Start sync metadata request PHP Fatal error:  Uncaught Kafka\Exception: Not has broker can connection `metadataBrokerList` in /Users/crotez/power/app/common/packages/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:252

### ISSUE THREAD

**Issue by CalmBo** [weiboad/kafka-php#270]
Start sync metadata request
PHP Fatal error:  Uncaught Kafka\Exception: Not has broker can connection `metadataBrokerList` in /Users/crotez/power/app/common/packages/vendor/nmred/kafka-php/src/Kafka/Consumer/Process.php:252

**Comment by basit-tkxel** [comment]
@CalmBo have you found any solution of your error?
