### ISSUE TITLE
Multiple instances of consumer processing same messages.

### ISSUE THREAD

**Issue by appasahebs** [weiboad/kafka-php#62]
I am using this kafka client and its working for me properly for single instance of consumer. If I am running 2 - 3 instances of same consumer with respective to the group name all instances processing same messages. But I am expecting processed(committed) messages should not consume by other consumer if group name is same.

Consumer.php
1 Topic  - test
3 Partitions - 0,1.2
Group name - testgroup

Running separate instances of consumer file. Randomly producing messages in each partitions.
php consumer.php
php consumer.php
php consumer.php 

After message consumed, commiting same message. But all partitions are consuming on each consumer. Am I missing something?

**Comment by nmred** [comment]
@appasahebs 

You can try using the new version.
