### ISSUE TITLE
update partition offset for myself

### ISSUE THREAD

**Issue by wj5346599** [weiboad/kafka-php#65]
I want update the offset with partition,but how to know the offset and how to calculate the current offset in the consumer's loop,it's my code:

<pre><code>$consumer = \Kafka\Consumer::getInstance('localhost:2181');
$consumer->setGroup('testgroup');
$consumer->setPartition('aatest-1', 0);
$consumer->setPartition('aatest-1', 1);
$consumer->setPartition('aatest-1', 2);
//$consumer->setTopic('aatest-1');
//while (1) {
$result = $consumer->fetch();
foreach ($result as $topicName => $partition) {
    foreach ($partition as $partId => $messageSet) {
        // var_dump($partition->getHighOffset())."-";
        foreach ($messageSet as $message) {
                //var_dump((string)$message);
               // on this,I will to do somethings with the message,if false,not update the offset,if true,call the commitOffset
        }
        //$offset = $partition->getMessageOffset();
    }
}

//up the offset
function commitOffset($topicName, $partition, $highOffset)
{
    echo $partition . "-" . $highOffset."\n";
//    exit;
    $data = array(
        'group_id' => 'testgroup',
        'data' => array(
            array(
                'topic_name' => 'aatest-1',
                'partitions' => array(
                    array(
                        'partition_id' => $partition,
                        'offset' => $highOffset,
                    ),
                ),
            ),
        ),
    );

    $conn = new \Kafka\Socket('locahost', '9092');
    $conn->connect();
    $encoder = new \Kafka\Protocol\Encoder($conn);
    $encoder->commitOffsetRequest($data);
    $decoder = new \Kafka\Protocol\Decoder($conn);
    $result = $decoder->commitOffsetResponse();
    var_dump($result);
}
</code></pre>

**Comment by nmred** [comment]
@wj5346599 

You can try using the new version.
