### ISSUE TITLE
Problem in install zookeeper extension in windows(Xampp)

### ISSUE THREAD

**Issue by lalitktechfour** [weiboad/kafka-php#67]
Hello,
     I am not able to get zookeeper class in php....Please suggest. How can i get zookeeper ext...

I got error messeage: Uncaught exception 'RuntimeException' with message 'ZooKeeper not found' in C:\xampp\htdocs\kafka\code\autoloader.php:38 Stack trace: #0 [internal function]: {closure}('ZooKeeper') #1 C:\xampp\htdocs\kafka\src\Kafka\ZooKeeper.php(103): spl_autoload_call('ZooKeeper') #2 C:\xampp\htdocs\kafka\src\Kafka\Consumer.php(121): Kafka\ZooKeeper->__construct('localhost:2181', NULL) #3 C:\xampp\htdocs\kafka\src\Kafka\Consumer.php(103): Kafka\Consumer->__construct('localhost:2181', NULL) #4 C:\xampp\htdocs\kafka\code\Consumer_test.php(39): 

Please suggest.

**Comment by Crim** [comment]
You can get the zookeeper extension via pecl: https://pecl.php.net/package/zookeeper
