### ISSUE TITLE
How to consume only new message from kafka

### ISSUE THREAD

**Issue by lalitktechfour** [weiboad/kafka-php#68]
Hello,
     I am not able to understand to how i consume only new message from kafka topic.. Please suggest:

I m using code as given below

$consumer = \Kafka\Consumer::getInstance('localhost:2181');
$group = 'updation';
$consumer->setGroup($group);
$consumer->setFromOffset(false);
//$consumer->setPartition('recom_page', 0);
$consumer->setTopic('updation',0);
$consumer->setMaxBytes(102400);
$result = $consumer->fetch();
$message_array = '';
foreach ($result as $topicName => $partition) {
    foreach($partition as $partId => $messageSet){
         foreach ($messageSet as $message) {
            var_dump((string)$message);
             }

```
}
```

}

**Comment by ayoob-faraji** [comment]
Hello
I think you must set true for offset , I mean  " $consumer->setFromOffset(true);" or you can omit this line in your code ( $consumer->setFromOffset(false) ) because The default value for offset is true and you do not need to set true for offset
