### ISSUE TITLE
Support for KeyedMessages

### ISSUE THREAD

**Issue by pcejrowski** [weiboad/kafka-php#78]
Hi,
I don't know how to create KeyedMessage to be sent to Kafka.
Could you please provide an example or just say whether it is possible.
Regards.

**Comment by Crim** [comment]
This library currently does not support message keys.  

https://github.com/nmred/kafka-php/blob/master/src/Kafka/Protocol/Encoder.php#L355-L356

**Comment by nmred** [comment]
You can try using the new version. v0.2.0 hash support send key -> value
