### ISSUE TITLE
Unexpected EOF while reading 4 bytes from stream (no data)

### ISSUE THREAD

**Issue by yuebin1009** [weiboad/kafka-php#80]
my service 
kafka 0.10.1.0 address http://archive.apache.org/dist/kafka/0.10.1.0/
php 5.3.21

**Comment by Chenimal** [comment]
Having the same issue. It happens when finishing consuming one partition and starting next one.

@yuebin1009 找到解决方法了么?

**Comment by nmred** [comment]
@yuebin1009 
@Chenimal 

You can try using the new version.
