### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by helww** [weiboad/kafka-php#85]
Hi,  nmred:
I am using your php kafka extension, Here is my question:
1, How to fetch only one message when consumer is running?
2, How to know that Message exists or not in the topic partition?

**Comment by nmred** [comment]
1. Not support fetch only one message, Can you talk about your specific needs?
2. You can reference example code https://github.com/weiboad/kafka-php/blob/master/example/Consumer.php#L24-L29

example:

```
if ($partition->getHighOffset() > $partition->getMessageOffset()) {
...... message exists
} else {
..... message not exists
}
```

**Comment by helww** [comment]
First, consumer always start from last offset.
Now queue is just like [100, 101, 102, ...], and No. 100 is the last offset.
If function fetch() takes [100, 101, 102], last offset is changed to 103. 
Luckily consumer is running very well, and that's ok. But Sometimes consumer has a long flow, and An error has occurred in one flow.
And processing message is nothing(dropped down or redo), and the consumer maybe crashed, So what about other unprocessed messages?

If fetch takes just one message, this situation will not happen, at least other unprocessed messages will not be affected.

**Comment by nmred** [comment]
By setting consumer maxbytes restrict fetch message, You can estimate the message size.

```
$consumer->setMaxBytes(102400);
```
