### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by phm3** [weiboad/kafka-php#86]
I am working with 2 clusters, and I am having issues with closing connections to A in order to use B cluster.

**Comment by nmred** [comment]
Can you describe it in detail?

**Comment by phm3** [comment]
In before route (using fatfree framework) I call cluster A, and produce message. Other class S should call another cluster B and produce message there. And it seems every time, I hit topic/partition is not found, because it always referrers to cluster A. 

Class S extends controller with before route.

**Comment by nmred** [comment]
@phm3 

You can use two produce instance, cluster A corresponding Instance A, cluster B corresponding Instance B, Or you can derict use  \Kafka\Protocol\Encoder and \Kafka\Protocol\Decoder send produce request, example can refer :https://github.com/weiboad/kafka-php/blob/master/example/SimpleProduce.php

**Comment by nmred** [comment]
If use \Kafka\Protocol\Encoder and \Kafka\Protocol\Decoder you need maintenance connect self

**Comment by phm3** [comment]
Thank you, I haven't tested yet \Kafka\Protocol\Decoder (Encoder)

**Comment by nmred** [comment]
I recomend you use tow instance solve this issue, because use  \Kafka\Protocol\Decoder (Encoder) method need you get kafka metadata mapping partion and broker, use \Kafka\Produce simply

**Comment by phm3** [comment]
The issue can be closed, I suspect it is a problem of the framework I use.
