### ISSUE TITLE
Cannot connect to any kafka brokers

### ISSUE THREAD

**Issue by no1youknowz** [weiboad/kafka-php#87]
Hi,

Using the example without zookeeper.

	$hostList = '192.168.85.181:2181';

	$produce = \Kafka\Produce::getInstance(null, null, $hostList);
	// get available partitions
	$partitions = $produce->getAvailablePartitions('MyFirstTopic1');
	var_dump($partitions);
	// send message
	$produce->setRequireAck(-1);
	$produce->setMessages('test', 0, array('test11111110099090'));
	$produce->setMessages('test', 0, array('test22222220099090'));
	$result = $produce->send();
	var_dump($result);

The PHP Error:

	An uncaught Exception was encountered

	Type: Kafka\Exception

	Message: Could not connect to any kafka brokers

	Filename: ../vendor/nmred/kafka-php/src/Kafka/MetaDataFromKafka.php

	Line Number: 202

The zookeeper log file:

	[2017-03-27 15:59:25,305] INFO Accepted socket connection from /192.168.85.185:56502 (org.apache.zookeeper.server.NIOServerCnxnFactory)
	[2017-03-27 15:59:25,309] WARN Exception causing close of session 0x0 due to java.io.IOException: Unreasonable length = 223181126 (org.apache.zookeeper.server.NIOServerCnxn)
	[2017-03-27 15:59:25,309] INFO Closed socket connection for client /192.168.85.185:56502 (no session established for client) (org.apache.zookeeper.server.NIOServerCnxn)

Using Kafka version: 0.10.2.0

Thanks

**Comment by no1youknowz** [comment]
I downgraded to 0.9.0.1.

	[root@localhost kafka_2.11-0.9.0.1]# [2017-03-27 06:49:59,685] INFO Accepted socket connection from /192.168.85.185:56506 (org.apache.zookeeper.server.NIOServerCnxnFactory)
	[2017-03-27 06:49:59,693] WARN Exception causing close of session 0x0 due to java.io.IOException: Unreasonable length = 74737011 (org.apache.zookeeper.server.NIOServerCnxn)
	[2017-03-27 06:49:59,693] INFO Closed socket connection for client /192.168.85.185:56506 (no session established for client) (org.apache.zookeeper.server.NIOServerCnxn)

Looks like same problem.

**Comment by no1youknowz** [comment]
Following the instructions from here:

    http://stackoverflow.com/a/27194583

and instead of using 0.0.0.0, I am using the IP of the server.

I'm now getting:

	array(1) { [0]=> int(0) } array(1) { ["test"]=> array(1) { [0]=> array(2) { ["errCode"]=> int(0) ["offset"]=> int(0) } } }

**Comment by nmred** [comment]
Hi, @no1youknowz 

Please refer https://github.com/weiboad/kafka-php/blob/master/example/ProduceWithoutZooKeeper.php

```
// use kafka host 
// $hostList = 'xxxx:9092'; that is kafka broker host:port
$produce = \Kafka\Produce::getInstance(null, null, $hostList);

// use zookeeper host connect kafka broker
// one param: zookeeper host:port
// two param is zk connect session timeout
$produce = \Kafka\Produce::getInstance('127.0.0.1:2181', 3000);

```

**Comment by no1youknowz** [comment]
I'm doing exactly that!

I'm now going to compile the ZooKeeper php extension and then test with 0.10.2.0.  

Before I close the ticket.

**Comment by no1youknowz** [comment]
So with 0.9.x seems to work fine.

With 0.10.2.0 I am getting:

	Type: Kafka\Exception\SocketEOF

	Message: Unexpected EOF while reading 4 bytes from stream (no data)

	Filename: /mnt/hgfs/Share/development/ecomzilladev/application/vendor/nmred/kafka-php/src/Kafka/Socket.php

	Line Number: 286

There are 3 outstanding tickets the same issue!

https://github.com/weiboad/kafka-php/issues/6
https://github.com/weiboad/kafka-php/issues/69
https://github.com/weiboad/kafka-php/issues/81

How to fix?

Thanks
