### ISSUE TITLE
Why the ZooKeeper Class Construct function has new ZooKeeper

### ISSUE THREAD

**Issue by muyline** [weiboad/kafka-php#88]
I found the file src\Kafka\ZooKeeper.php,in the contruct function,the code is 
`public function __construct($hostList, $timeout = null)
    {
        if (!is_null($timeout) && is_numeric($timeout)) {
            $this->zookeeper = new \ZooKeeper($hostList, null, $timeout);
        } else {
            $this->zookeeper = new \ZooKeeper($hostList);
        }
    }`
the \ZooKeeper is not exist。

**Comment by nmred** [comment]
\ZooKeeper is php extension `zookeeper` class, if you use \Kafka\ZooKeeper need you install zookeeper.so in your php env
