### ISSUE TITLE
v0.1.6 client get stream is not free

### ISSUE THREAD

**Issue by jaylu163** [weiboad/kafka-php#89]
` 
public function __construct($hostList, $timeout = null){

       if (!is_null($timeout) && is_numeric($timeout)) {
            $this->zookeeper = new \ZooKeeper($hostList, null, $timeout);
        } else {
            $this->zookeeper = new \ZooKeeper($hostList);
        }
}
`

这个不是一个单例。导致 kafka会有很多个链接数

是不是可以改为：

`
public function __construct($hostList, $timeout = null) {
        if (!is_null($timeout) && is_numeric($timeout)) {
            if($this->zookeeper ==null){
                $this->zookeeper = new \ZooKeeper($hostList, null, $timeout);
            }
           return $this->zookeeper;
        } else {
            if($this->zookeeper ==null){
                $this->zookeeper = new \ZooKeeper($hostList);
            }
           return $this->zookeeper;
        }

    }
`

**Comment by nmred** [comment]
kafka produce and consumer is single instance , could you describe in detail how you used it?

**Comment by nmred** [comment]
class `Kafka\Zookeeper` is not single instance, Current version only used kafka consumer, but \Kafka\Consumer is single instance, so `Kafka\Zookeeper`  not need single instance

**Comment by jaylu163** [comment]
$consumer->setGroup($group);
            $consumer->setTopic($topic);
           // $consumer->setMaxBytes(102400);
            $result = $consumer->fetch();

           path : src/kafka/Consumer.php

         this is  fetch method  
        public function fetch()
       {
        $data = $this->_formatPayload();
        if (empty($data)) {
            return false;
        }

        $streams = array();
        foreach ($data as $host => $requestData) {
            $connArr = $this->client->getStream($host);  // **stream is not single instance ,My tcp add          always** 
            $conn    = $connArr['stream'];
            $encoder = new \Kafka\Protocol\Encoder($conn);
            $encoder->fetchRequest($requestData);
            $streams[$connArr['key']] = $conn;

        }

        $fetch = new \Kafka\Protocol\Fetch\Topic($streams, $data);
        
        // register fetch helper
        $freeStream = new \Kafka\Protocol\Fetch\Helper\FreeStream($this->client);
        $freeStream->setStreams($streams);
        \Kafka\Protocol\Fetch\Helper\Helper::registerHelper('freeStream', $freeStream);

        // register partition commit offset
        $commitOffset = new \Kafka\Protocol\Fetch\Helper\CommitOffset($this->client);
        $commitOffset->setGroup($this->group);
        \Kafka\Protocol\Fetch\Helper\Helper::registerHelper('commitOffset', $commitOffset);

        $updateConsumer = new \Kafka\Protocol\Fetch\Helper\Consumer($this);
        \Kafka\Protocol\Fetch\Helper\Helper::registerHelper('updateConsumer', $updateConsumer);

        return $fetch;
    }

**Comment by jaylu163** [comment]
I can how to do ,please  guide.... thanks

**Comment by nmred** [comment]
You code is not already this line, this line will free connect
https://github.com/weiboad/kafka-php/blob/v0.1.6/src/Kafka/Consumer.php#L262
