### ISSUE TITLE
composer 安装失败

### ISSUE THREAD

**Issue by lingdi2000** [weiboad/kafka-php#94]
运行  php composer.phar install
提示：
 Problem 1
    - The requested package nmred/kafka-php 0.2.* is satisfiable by nmred/kafka-php[v0.2.0-beta] but these conflict with your requirements or minimum-stability.

新手，没用过composer 这个问题该怎么解决呢

**Comment by suchasplus** [comment]
Your minimum-stability by default is stable so yes nmred/kafka-php is not allowed to be installed as dev-master by that minimum-stability, either you require it with "@dev" as requirement, or you change the minimum-stability to dev.
