### ISSUE TITLE
请问下作者，你这个Kafka解析协议是从哪里知道的？

### ISSUE THREAD

**Issue by KomaBeyond** [weiboad/kafka-php#95]
就像我标题那样，比如说像你一样要写一个这种项目的话，首先得知道Kafka的数据存储协议，这样读出来才能解析或者通过Socket和它交互，请问你一下，这个协议你是从哪里看到的，可以给个链接么？

另外好几天了看github的 trending，看到你这个项目，我想先看看协议然后明白的话准备深入学习下你这个项目。

**Comment by nmred** [comment]
@KomaBeyond 

You can reference kafka wiki:

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol
http://kafka.apache.org/protocol.html#protocol_preliminaries
