### ISSUE TITLE
SSL Connection

### ISSUE THREAD

**Issue by romaco1** [weiboad/kafka-php#96]
How to configure Producer to use SSL connection?

**Comment by nmred** [comment]
The next version(v0.2.1) supports SSL connections

**Comment by romaco1** [comment]
Please add doc or example how to use SSL.

**Comment by jinguoxing** [comment]
我本地有几个ssl的文件
ca-cert
ca-cert.srl
ca-key
kafka.keystore
kafka.truststore


 $config->setSslLocalCert('/XXX/ca-cert');
 $config->setSslLocalPk('/XXX/ca-key');
  $config->setSslEnable(true);
 $config->setSslPassphrase('passwd');

是这样写么？不起作用

**Comment by basildevasia** [comment]
Hi @nmred ,
**_SSL Support_**
Is there any support for the below? Couldn't find the functions setSslLocalCert, setSslLocalPk, setSslEnable, setSslPassphrase or setSslPeerName defined in the composer package. 
The latest package i can find is "nmred/kafka-php": "v0.2.0.8"
The regular case works fine. Would be great to have the SSL support

// if use ssl connect
$config->setSslLocalCert('/home/vagrant/code/kafka-php/ca-cert');
$config->setSslLocalPk('/home/vagrant/code/kafka-php/ca-key');
$config->setSslEnable(true);
$config->setSslPassphrase('123456');
$config->setSslPeerName('nmred');
